global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: product-service
    metrics_path: /metrics
    static_configs:
      - targets: ["product-service:3000"]

  - job_name: inventory-service
    metrics_path: /metrics
    static_configs:
      - targets: ["inventory-service:3001"]

  - job_name: order-service
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:3002"]
